<!DOCTYPE Jogadores [
    <!ELEMENT Jogadores (Jogador*)>
    <!ELEMENT Jogador (nome, nivel, raca, classe)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
    <!ELEMENT raca (#PCDATA)>
    <!ELEMENT classe (#PCDATA)>
]>

<Jogadores>
    <Jogador>
        <nome>Celso</nome>
        <nivel>1</nivel>
        <raca>HUMANO</raca>
        <classe>MAGO</classe>
    </Jogador>
    <Jogador>
        <nome>Gabriel</nome>
        <nivel>1</nivel>
        <raca>HUMANO</raca>
        <classe>GUERREIRO</classe>
    </Jogador>
</Jogadores>