<!DOCTYPE Monstros [
    <!ELEMENT Monstros (Monstro*)>
    <!ELEMENT Monstro (nome, poder, tesouros, niveisPerdidos)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT poder (#PCDATA)>
    <!ELEMENT tesouros (#PCDATA)>
    <!ELEMENT niveisPerdidos (#PCDATA)>
]>

<Monstros>
    <Monstro>
        <nome>Drag√£o Vermelho</nome>
        <poder>3</poder>
        <tesouros>2</tesouros>
        <niveisPerdidos>2</niveisPerdidos>
    </Monstro>
    <Monstro>
        <nome>Esqueleto Misterioso</nome>
        <poder>2</poder>
        <tesouros>1</tesouros>
        <niveisPerdidos>1</niveisPerdidos>
    </Monstro>
</Monstros>